"""Printed gears (0.5M: 7T pinion, 36T wheel gear): the alternative to the brass pair (Gears.wheel_gear).

The robot now runs the bought brass pair: the 7T pinions pressed on the motors, the 36T drilled and screwed to the
printed wheel (drive.wheel, gear_guide.py). With Gears.wheel_gear = "printed" the wheel carries its own printed
gear (generated here) instead; it meshes with the brass pinion too, with about 0.2 mm of backlash (the printed
wheel's -0.45 profile shift isn't made up by the brass pinion: tools/check_gears.py).

Same module, tooth counts, widths and centre distance as the brass pair, so they drop into the same places. The
teeth are generated by py_gearworks (involute, with the undercut a rack cutter would make). A 7-tooth pinion cut
to the standard profile is deeply undercut (weak roots, poor contact), so the printed pair is profile shifted: +0.45
on the pinion, -0.45 on the wheel (the shifts cancel, the centre distance stays 10.75). That shift would make the
pinion's tip pointed, so its addendum is cut by 0.2 module: the tip land is then about 0.22 mm, the contact ratio
1.25. The printed pair has 0.12 mm of backlash: round 6's 0.06 printed with none left (over-cure fattens the teeth
and both prints closed the mesh by about 0.06-0.09 mm).

Print them in resin (tough / ABS-like if available), axis vertical, lifted on supports (on the plate, the first
layers would flare the teeth). A printed pinion is glued on: a press fit would split the thin resin (pinions(): two
bores to try on the shaft).
"""

from dataclasses import dataclass

import py_gearworks as pg
from build123d import Cylinder, Pos

from .params import P, Params


@dataclass(frozen=True)
class PrintedGears:
    # profile shift and pinion tip cut: Gears.shift / Gears.tip_cut (the layout's clearances use them)
    dedendum: float = 1.25  # both (module): 0.25 m of tip clearance
    # backlash per gear, module units along the line of action: the pair has 0.12 mm, most of it on the wheel (its
    # teeth have the wider tips); a print error may close 0.19 mm of centre distance before the teeth bind
    # (tools/check_gears.py). Round 6 had 0.06 mm (0.06 each): both pairs printed with none left, the left one tight
    backlash_pinion: float = 0.10
    backlash_wheel: float = 0.14
    tip_fillet: float = 0.1  # module
    pinion_bores: tuple = (1.07, 1.03)  # motor shaft 1.0, glued: 1.07 at 2.5 s, and a tighter one


PG = PrintedGears()


def brass_spec(z, height, p: Params = P):
    """py_gearworks stand-in for a bought gear (standard, unshifted; for the pictures)."""
    return pg.SpurGear(number_of_teeth=z, module=p.gears.module, height=height, dedendum_coefficient=1.25,
                       backlash=0.05, enable_undercut=True)


def spec(z, height, pg_: PrintedGears = PG, p: Params = P, backlash=None):
    """py_gearworks gear for one of the two tooth counts (the pinion or the wheel gear)."""
    g = p.gears
    pinion = z == g.pinion_z
    if backlash is None:
        backlash = pg_.backlash_pinion if pinion else pg_.backlash_wheel
    return pg.SpurGear(number_of_teeth=z, module=g.module, height=height,
                       profile_shift=g.shift if pinion else -g.shift,
                       addendum_coefficient=1.0 - (g.tip_cut if pinion else 0.0),
                       dedendum_coefficient=pg_.dedendum, backlash=backlash, tip_fillet=pg_.tip_fillet,
                       enable_undercut=True)


def _gear(z, height, bore, label, pg_, p, backlash=None):
    """Local frame of purchased.spur: axis on +Z, outer face at z=0, body towards -Z."""
    part = Pos(0, 0, -height) * spec(z, height, pg_, p, backlash).build_part()
    part -= Cylinder(bore / 2, 2 * height)
    part.label, part.color = label, (0.95, 0.95, 0.9)
    return part


def pinion(pg_: PrintedGears = PG, p: Params = P, bore=None):
    bore = pg_.pinion_bores[0] if bore is None else bore
    return _gear(p.gears.pinion_z, p.gears.pinion_w, bore, "gear_pinion", pg_, p)


def pinions(pg_: PrintedGears = PG, p: Params = P):
    """{label: pinion}: one per bore in pinion_bores (gear_pinion_107, gear_pinion_103: the bore in hundredths)."""
    out = {}
    for bore in pg_.pinion_bores:
        part = pinion(pg_, p, bore)
        part.label = f"gear_pinion_{round(bore * 100)}"
        out[part.label] = part
    return out


def wheel_gear(pg_: PrintedGears = PG, p: Params = P):
    """The wheel's gear ring (drive.wheel adds the rest): its bore clears the tube."""
    return _gear(p.gears.wheel_z, p.gears.wheel_w, p.wheel_hole_d, "gear_wheel", pg_, p)


def placed(side, pg_: PrintedGears = PG, p: Params = P):
    """{"wheel_gear_X": ..., "pinion_X": ...} in the robot frame, where the layout puts the bought gears, with the
    teeth in mesh (for the viewer and renders; the layout's clash checks keep the tip-circle stand-ins)."""
    import numpy as np
    from build123d import Rot
    g = p.gears
    s = 1 if side > 0 else -1
    tag = "L" if side > 0 else "R"
    mx, mz = p.motor_axis(side)
    # local frame (purchased.spur): axis +Z, outer face at z=0; Rot(-90 * s, 0, 0) takes it into the robot,
    # local y going to robot -z (left) or +z (right)
    target = np.array([mx, -s * (mz - p.axle_z), 0.0])
    brass = g.wheel_gear == "brass"  # the brass pair (the printed pinions are no longer used)
    w = brass_spec(g.wheel_z, g.wheel_w, p) if brass else spec(g.wheel_z, g.wheel_w, pg_, p)
    pn = brass_spec(g.pinion_z, g.pinion_w, p)
    pn.mesh_to(w, target_dir=target / np.linalg.norm(target))
    out = {}
    for gear, bore, y_outer, name in ((w, p.wheel_hole_d, p.gear_y + g.wheel_w, "wheel_gear"),
                                      (pn, g.pinion_bore, p.pinion_y, "pinion")):
        h = g.wheel_w if gear is w else g.pinion_w
        cx, cy = gear.center[:2]
        part = Pos(0, 0, -h) * gear.build_part()
        part -= Pos(cx, cy, 0) * Cylinder(bore / 2, 2 * h + 2)
        part = Pos(0, s * y_outer, p.axle_z) * Rot(-90 * s, 0, 0) * part
        if brass and name == "wheel_gear":  # its drilled holes
            from .drive import along_y, brass_gear
            disc = along_y(g.tip_d(g.wheel_z) / 2 + 0.1, s * p.gear_y, s * (p.gear_y + g.wheel_w), 0, p.axle_z)
            part -= disc - brass_gear(side, p)
        part.label, part.color = f"{name}_{tag}", (0.85, 0.7, 0.3)
        out[part.label] = part
    return out
