"""Printed stand-ins for the brass gears (0.5M: 7T pinion, 36T wheel gear) while the bought ones are on their way.

Same module, tooth counts, widths and centre distance as the brass pair, so they drop into the same places. The
teeth are generated by py_gearworks (involute, with the undercut a rack cutter would make). A 7-tooth pinion cut
to the standard profile is deeply undercut (weak roots, poor contact), so the pair is profile shifted: +0.45 on
the pinion, -0.45 on the wheel (the shifts cancel, the centre distance stays 10.75). That shift would make the
pinion's tip pointed, so its addendum is cut by 0.2 module: the tip land is then 0.24 mm, the contact ratio 1.25.
The printed gears go together as a pair; don't mix one with a brass gear (the brass pair is probably unshifted).

Print them in resin (tough / ABS-like if available), axis vertical, lifted on supports (on the plate, the first
layers would flare the teeth). Drill the bores to size and glue: a press fit would split the thin resin.
"""

from dataclasses import dataclass

import py_gearworks as pg
from build123d import Cylinder, Pos

from .params import P, Params


@dataclass(frozen=True)
class PrintedGears:
    # profile shift and pinion tip cut: Gears.shift / Gears.tip_cut (the layout's clearances use them)
    dedendum: float = 1.25  # both (module): 0.25 m of tip clearance
    backlash: float = 0.06  # per gear, module units along the line of action: the pair has 0.06 mm (the
    # eccentric sleeves then set the running backlash; they close 0.09 mm of centre distance before binding)
    tip_fillet: float = 0.1  # module
    pinion_bore: float = 1.0  # motor shaft 1.0: drill 1.0, glue
    wheel_bore: float = 2.0  # axle 2.0: drill 2.0, glue


PG = PrintedGears()


def spec(z, height, pg_: PrintedGears = PG, p: Params = P):
    """py_gearworks gear for one of the two tooth counts (the pinion or the wheel gear)."""
    g = p.gears
    pinion = z == g.pinion_z
    return pg.SpurGear(number_of_teeth=z, module=g.module, height=height,
                       profile_shift=g.shift if pinion else -g.shift,
                       addendum_coefficient=1.0 - (g.tip_cut if pinion else 0.0),
                       dedendum_coefficient=pg_.dedendum, backlash=pg_.backlash, tip_fillet=pg_.tip_fillet,
                       enable_undercut=True)


def _gear(z, height, bore, label, pg_, p):
    """Local frame of purchased.spur: axis on +Z, outer face at z=0, body towards -Z."""
    part = Pos(0, 0, -height) * spec(z, height, pg_, p).build_part()
    part -= Cylinder(bore / 2, 2 * height)
    part.label, part.color = label, (0.95, 0.95, 0.9)
    return part


def pinion(pg_: PrintedGears = PG, p: Params = P):
    return _gear(p.gears.pinion_z, p.gears.pinion_w, pg_.pinion_bore, "gear_pinion", pg_, p)


def wheel_gear(pg_: PrintedGears = PG, p: Params = P):
    return _gear(p.gears.wheel_z, p.gears.wheel_w, pg_.wheel_bore, "gear_wheel", pg_, p)


def placed(side, pg_: PrintedGears = PG, p: Params = P):
    """{"wheel_gear_X": ..., "pinion_X": ...} in the robot frame, where the layout puts the bought gears, with the
    teeth in mesh (for the viewer and renders; the layout's clash checks keep the tip-circle stand-ins)."""
    import numpy as np
    from build123d import Rot
    g = p.gears
    s = 1 if side > 0 else -1
    tag = "L" if side > 0 else "R"
    mx, mz = p.motor_axis(side)
    # local frame (purchased.spur): axis +Z, outer face at z=0; Rot(-90 * s, 0, 0) takes it into the robot,
    # local y going to robot -z (left) or +z (right)
    target = np.array([mx, -s * (mz - p.axle_z), 0.0])
    w = spec(g.wheel_z, g.wheel_w, pg_, p)
    pn = spec(g.pinion_z, g.pinion_w, pg_, p)
    pn.mesh_to(w, target_dir=target / np.linalg.norm(target))
    out = {}
    for gear, bore, y_outer, name in ((w, pg_.wheel_bore, p.gear_y + g.wheel_w, "wheel_gear"),
                                      (pn, pg_.pinion_bore, p.pinion_y, "pinion")):
        h = g.wheel_w if gear is w else g.pinion_w
        cx, cy = gear.center[:2]
        part = Pos(0, 0, -h) * gear.build_part()
        part -= Pos(cx, cy, 0) * Cylinder(bore / 2, 2 * h + 2)
        part = Pos(0, s * y_outer, p.axle_z) * Rot(-90 * s, 0, 0) * part
        part.label, part.color = f"{name}_{tag}", (0.85, 0.7, 0.3)
        out[part.label] = part
    return out
